database:
  path: LineCoverage-dataset/icra20_dataset
  data_dir: ww2
problem: slc
solver_slc: beta3_atsp
solver_mlc: mem
cost_function: travel_time
travel_time_config:
  service_speed: 0.5
  deadhead_speed: 0.5
  wind_speed: 0.0
  wind_dir: 45
add_pairwise_nonreq_edges: false
convert_osm_json: true
capacity: 1000000
use_2opt: false
ilp_time_limit: 100000000
depot:
  mode: custom
  ID: 9728365302
input_graph:
  lla: true
  costs: false
plot_input_graph:
  name: graph
  plot: true
  plot_nreq_edges: false
writeGeoJSON:
  write: true
  filename: graph.json
  var_name: graph_data
  non_req_edges: false
route_output:
  plot: true
  kml: true
  data: true
  geojson: true
  edge_data: true
  agg_results: true
  append: false
  clear_dir: false
filenames:
  map_json: map_data.json
  nodes_ll: node_list_lat_long
  nodes_data: node_data
  req_edges: req_edge_list
  nonreq_edges: non_req_edge_list